/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef doc_CONSTANTS_H
#define doc_CONSTANTS_H

#include "doc_types.h"

namespace tutorial {

class docConstants {
 public:
  docConstants();

};

extern const docConstants g_doc_constants;

} // namespace

#endif
